### ISSUE TITLE
the tutorials of SPATA

### ISSUE THREAD

**Issue by l-magnificence** [kueckelj/SPATA#11]
This is a very nice package for spatial transcriptome, hoping the tutorial of SPATA can be completed for more people to use.
In your preprint paper you mentioned the possibility to implement each vector, for example “latent time” extracted from RNA-velocity using scvelo, to integrate into SPATA object, but I can't find the associated tutorials in detail about it.
And can SPATA be completely replaced by SPATA2?

**Comment by heilandd** [comment]
Thanks for you comment. Yes SPATA2 is the new version and can be fully replaced, also new functions and tutorials are available on the SPATA2 webpage. 

The velocity functions are not supported anymore. The problem is that the model of RNA velocity is based on the assumption of a single cell, using it on spatial data has met with considerable resistance. 

RNA velocity was designed to decipher dynamics within short timeframes from single cell data. Since you are not aware of you cellular composition within each spot, the analysis of velocity is biased or potentially flawed. Even if you are aware of your cellular composition (e.g. cancer only), the noise through ambiguous inter-spot heterogeneity can be assumed as an insurmountable obstacle to extracting meaningful signals. This does not apply to regional synchronisation of transcriptional states, where velocity could identify meaningful trajectories.
Another factor: Within scRNA-seq data, we determine the velocity from dimension reductions, UMAP/DC/PCA...., which already represent an approximation to transcriptional similarity. Only if this is given in the spatial data (which is often the case) can spatial coordinates be used. 

Since the Visium technology has not a single-cell resolution we will not longer use/support RNA velocity.  If you can proof a stable cellular composition within your spatial data (spots) you can use RNA-velocity. The integration to scVelo still exists in the development branch. 

The function called: "getRNAvelocity", which uses the loom file and a SPATA object of your Visium dataset to merge both (through the seurat wrapper). Data will be exported to a hd5 file which can be used for scVelo. A python script (https://github.com/theMILOlab/SPATA/blob/Development/data/scvelo.py) will be used to perform the spatial integration in scVelo.
We working to implement a spatial velocity, hopefully coming soon. Additionally, we will implement RNA-velocity for the Visum HD. 

Best regards, 
SPATA Team
